MediaMonitoring/Models/AdCluster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class AdCluster
    {
        public string Product { get; set; }
        public string Station { get; set; }
        public string Brand { get; set; }
        public int Sun { get; set; }
        public int Mon { get; set; }
        public int Tue { get; set; }
        public int Wed { get; set; }
        public int Thu { get; set; }
        public int Fri { get; set; }
        public int Sat { get; set; }
    }

    public class AdClusterPress
    {
        public string Product { get; set; }
        public string Publication { get; set; }
        public string Brand { get; set; }
        public int Sun { get; set; }
        public int Mon { get; set; }
        public int Tue { get; set; }
        public int Wed { get; set; }
        public int Thu { get; set; }
        public int Fri { get; set; }
        public int Sat { get; set; }
    }

    public class AdClusterOutdoor
    {
        public string Product { get; set; }
        public string State { get; set; }
        public string Brand { get; set; }
        public int Sun { get; set; }
        public int Mon { get; set; }
        public int Tue { get; set; }
        public int Wed { get; set; }
        public int Thu { get; set; }
        public int Fri { get; set; }
        public int Sat { get; set; }
    }

    public class AdClusterAllMedia
    {
        public string Product { get; set; }
        public string Medium { get; set; }
        public string Brand { get; set; }
        public string Station { get; set; }
        public string TimeBand { get; set; }
        public string Time { get; set; }
        public string PROGRAM { get; set; }
        public DateTime Addate { get; set; }
        public int Spots { get; set; }
        public double Duration { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Advertiser { get; set; }
        public string Quarter { get; set; }
    }
}

MediaMonitoring/Models/AdClusterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class AdClusterViewModel
    {
        public IEnumerable<AdCluster> AdClusters { get; set; }
        public IEnumerable<AdClusterPress> AdClusterPresses { get; set; }
        public IEnumerable<AdClusterOutdoor> AdClusterOutdoors { get; set; }
        public IEnumerable<AdClusterByMonth> AdClusterByMonths { get; set; }
        public IEnumerable<AdClusterByMonthPress> AdClusterByMonthPresses { get; set; }
        public IEnumerable<AdClusterByMonthOutdoor> AdClusterByMonthOutdoors { get; set; }
        public IEnumerable<AdClusterByTimeSegment> AdClusterByTimeSegments { get; set; }
        public IEnumerable<AdClusterByTimeSegmentPress> AdClusterByTimeSegmentPresses { get; set; }
        public IEnumerable<AdClusterByTimeSegmentOutdoor> AdClusterByTimeSegmentOutdoors { get; set; }
        public IEnumerable<AdClusterByWeek> AdClusterByWeeks { get; set; }
        public IEnumerable<AdClusterByWeekPress> AdClusterByWeekPresses { get; set; }
        public IEnumerable<AdClusterByWeekOutdoor> AdClusterByWeekOutdoors { get; set; }
        public IEnumerable<AdClusterByMaterialLength> AdClusterByMaterialLengths { get; set; }
        public IEnumerable<AdClusterByMaterialLengthPress> AdClusterByMaterialLengthPresses { get; set; }
        public IEnumerable<AdClusterByMaterialLengthOutdoor> AdClusterByMaterialLengthOutdoors { get; set; }
        public IEnumerable<AdClusterAllMedia> AdClusterAllMedias { get; set; }
    }
}

MediaMonitoring/Models/MediaSpend.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class MediaSpend
    {
        public string Advertiser { get; set; }
        public int Spots { get; set; }
        public double Value { get; set; }
    }
}

MediaMonitoring/Models/MediaSpendViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class MediaSpendViewModel
    {
        public IEnumerable<MediaSpend> MediaSpends { get; set; }
        public IEnumerable<MediaSpendByBrand> MediaSpendByBrands { get; set; }
        public IEnumerable<MediaSpendByProduct> MediaSpendByProducts { get; set; }
    }
}

MediaMonitoring/Models/Reconciliation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class Reconciliation
    {
        public DateTime AdDate { get; set; }
        public int CapturedSpots { get; set; }
        public int ScheduledSpots { get; set; }
        public string Program { get; set; }
        public string Stations { get; set; }
        public string ScheduledTime { get; set; }
        public string CapturedTime { get; set; }
        public int CapturedExtra { get; set; }
        public string Brand { get; set; }
        public string Identifier { get; set; }
        public string Client { get; set; }
        public string Status { get; set; }
        public Decimal Spend { get; set; }
        public int ExtraSpots { get; set; }
    }

    public class ReconciliationSummary
    {
        //Stations, Program, NumberBooked, NumberCaptured, case when Position = 1 then UnScheduled else 0 End as UnScheduled, ScheduledTime, Brand, Identifier, Zone, DateSpec, ExtraSpots
        public string Program { get; set; }
        public string Stations { get; set; }
        public int NumberBooked { get; set; }
        public int NumberCaptured { get; set; }
        public int UnScheduled { get; set; }
        public string ScheduledTime { get; set; }
        public string Brand { get; set; }
        public string Identifier { get; set; }
        public string Zone { get; set; }
        public string DateSpec { get; set; }
        public int ExtraSpots { get; set; }
    }
}

MediaMonitoring/Models/ReconciliationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class ReconciliationViewModel
    {
        public IEnumerable<Reconciliation> Reconciliations { get; set; }
        public IEnumerable<ReconciliationSummary> ReconciliationSummaries { get; set; }
    }
}

MediaMonitoring/Models/WatchDogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaMonitoring.Models
{
    public class WatchDogViewModel
    {
        public IEnumerable<WatchDog> WatchDogs { get; set; }
        public IEnumerable<WatchDogRadio> WatchDogRadios { get; set; }
        public IEnumerable<WatchDogOutdoor> WatchDogOutdoors { get; set; }
        public IEnumerable<WatchDogPress> WatchDogPresses { get; set; }
        public IEnumerable<WatchDogSummary> WatchDogSummaries { get; set; }
        public IEnumerable<WatchDogSummaryPress> WatchDogSummaryPresses { get; set; }
        public IEnumerable<WatchDogSummaryOutdoor> WatchDogSummaryOutdoors { get; set; }
        public IEnumerable<WatchDogStationAudit> WatchDogStationAudits { get; set; }
        public IEnumerable<WatchDogStationAuditRadio> WatchDogStationAuditRadios { get; set; }
    }
}

MediaMonitoring/Controllers/ElectronicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using MediaMonitoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;

namespace MediaMonitoring.Controllers
{
    [Authorize]
    public class ElectronicController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext db;

        public ElectronicController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            db = context;
            this.userManager = userManager;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Dashboard(string search, string search2, string search3)
        {
            var userDetails = await db.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefaultAsync();
            ViewBag.User = userDetails.FirstName;

            //Get Total AdSpend
            DateTime date = DateTime.Now;
            int year = DateTime.Now.Year;
            var advertiserId = new SqlParameter("@AdvertizerId", userDetails.CompanyId);
            var productId = new SqlParameter("@ProductId", userDetails.CategoryId);
            var beginDate = new SqlParameter("@BeginDate", new DateTime(year, 1, 1));
            var endDate = new SqlParameter("@EndDate", new DateTime(year, 12, 31));
            var firstDayOfMonth = new DateTime(date.Year, date.Month, 1);

            //Get Media Mix
            var getMediaMix = db.MediaSpendMixes.FromSqlRaw("onl_GetMediaSpendAllMediaNewFormat_sel @BeginDate, @EndDate, @AdvertizerId", parameters: new[] { beginDate, endDate, advertiserId }).ToList();

            var resultOutput = getMediaMix.Where(x => x.AdvertizerId == userDetails.CompanyId && !x.Brand.StartsWith("OTHERS")).FirstOrDefault();

            var meds = new List<double>();
            if (resultOutput != null)
            {
                var tot = resultOutput.Total;
                var tel = resultOutput.TELE;
                tel = tel != 0 ? Math.Round(tel / tot * 100, 1) : 0;
                meds.Add(tel);

                var rad = resultOutput.RADIO;
                rad = rad != 0 ? Math.Round(rad / tot * 100, 1) : 0;
                meds.Add(rad);

                var pre = resultOutput.PRESS;
                pre = pre != 0 ? Math.Round(pre / tot * 100, 1) : 0;
                meds.Add(pre);

                var ooh = resultOutput.OUTDOOR;
                ooh = ooh != 0 ? Math.Round(ooh / tot * 100, 1) : 0;
                meds.Add(ooh);
            }

            ViewBag.Mediums = meds;

            //Bar chart Durations Mix
            var getDurationMix = db.DurationMixes.FromSqlRaw("onl_GetSpotsByDuration_sel @AdvertizerId, @BeginDate, @EndDate", parameters: new[] { advertiserId, beginDate, endDate }).ToList();

            ViewBag.Durations = getDurationMix.Select(x => x.Duration).ToList();
            ViewBag.DurCount = getDurationMix.Select(x => x.DurationCount).ToList();


            //Bar chart spend/spots            
            List<TopAdvertisers2> barData = null;
            List<TopAdvertisers3> barData2 = null;

            if (!string.IsNullOrEmpty(search3) && search3 != "Top Advertisers")
            {
                ViewBag.TopBar = search3;
                if (search3 == "Top Television Advertisers")
                {
                    barData = db.TopAdvertisers2s.FromSqlRaw("stp_GetMediaSpendTelevision_sel @BeginDate, @EndDate", parameters: new[] { beginDate, endDate }).ToList();

                    ViewBag.Advertizers = barData.Take(10).Select(x => x.Advertiser).ToList();
                    ViewBag.Spots = barData.Take(10).Select(x => x.Spots).ToList();
                }
                else if (search3 == "Top Radio Advertisers")
                {
                    barData = db.TopAdvertisers2s.FromSqlRaw("stp_GetMediaSpendRadio_sel @BeginDate, @EndDate", parameters: new[] { beginDate, endDate }).ToList();

                    ViewBag.Advertizers = barData.Take(10).Select(x => x.Advertiser).ToList();
                    ViewBag.Spots = barData.Take(10).Select(x => x.Spots).ToList();
                }
                else if (search3 == "Top Press Advertisers")
                {
                    barData2 = db.TopAdvertisers3s.FromSqlRaw("stp_GetMediaSpendPress_sel @BeginDate, @EndDate", parameters: new[] { beginDate, endDate }).ToList();

                    ViewBag.Advertizers = barData2.Take(10).Select(x => x.Advertiser).ToList();
                    ViewBag.Spots = barData2.Take(10).Select(x => x.Spots).ToList();
                }
                else if (search3 == "Top Outdoor Advertisers")
                {
                    barData2 = db.TopAdvertisers3s.FromSqlRaw("stp_GetMediaSpendOutdoor_sel @BeginDate, @EndDate", parameters: new[] { beginDate, endDate }).ToList();

                    ViewBag.Advertizers = barData2.Take(10).Select(x => x.Advertiser).ToList();
                    ViewBag.Spots = barData2.Take(10).Select(x => x.Spots).ToList();
                }
            }
            else
            {
                ViewBag.TopBar = "Top Advertisers";

                var getSpend2 = db.TopAdvertisers.FromSqlRaw("onl_GetMediaSpendAllMedia2_sel @BeginDate, @EndDate", parameters: new[] { beginDate, endDate }).ToList();

                ViewBag.Advertizers = getSpend2.Take(10).Select(x => x.Advertiser).ToList();
                ViewBag.Spots = getSpend2.Take(10).Select(x => x.Spots).ToList();
            }

            //SOE By Months
            var getSOEMonthsMix = db.CummulativeSOVSOEs.FromSqlRaw("onl_GetShareOfVoiceAllMediaSpendCummulativeStar_sel @ProductId, @BeginDate, @EndDate", parameters: new[] { productId, beginDate, endDate }).ToList();

            var getCompanyName = db.CodeFiles.Where(x => x.codefileid == "G" + userDetails.CompanyId).Select(x => x.Description).FirstOrDefault();

            var getSMM = getSOEMonthsMix.Where(x => x.Advertizer == getCompanyName).GroupBy(x => new { x.MonthValue, x.Month, x.Brand })
                .OrderBy(x => x.Key.MonthValue)
                .Select(x => new
                {
                    Months = x.Key.Month,
                    Brands = x.Key.Brand,
                    AllTotalSpend = x.Sum(x => x.TotalSpend)
                });

            var months = getSMM.Select(x => x.Months).Distinct().ToArray();
            ViewBag.Months = months;

            //line chart data single dataset
            ViewBag.Spends = getSMM.Select(x => x.AllTotalSpend).ToArray();


            //Total Advertizers List
            ViewBag.TopAdvertizersSelection = "This Year";
            if (search2 == "This Month")
            {
                beginDate = new SqlParameter("@BeginDate", firstDayOfMonth);
                endDate = new SqlParameter("@EndDate", firstDayOfMonth.AddMonths(1).AddDays(-1));
                ViewBag.TopAdvertizersSelection = search2;
            }
            else if (search2 == "Last Month")
            {
                beginDate = new SqlParameter("@BeginDate", firstDayOfMonth.AddMonths(-1));
                endDate = new SqlParameter("@EndDate", firstDayOfMonth.AddDays(-1));
                ViewBag.TopAdvertizersSelection = search2;
            }
            else
            {
                beginDate = new SqlParameter("@BeginDate", new DateTime(year, 1, 1));
                endDate = new SqlParameter("@EndDate", new DateTime(year, 12, 31));
            }

            var getSpend = db.TopAdvertisers.FromSqlRaw("stp_GetMediaSpendAllMedia_sel @BeginDate, @EndDate", parameters: new[] { beginDate, endDate }).ToList();

            var spendTotal = 0.00;
            var spend = new List<TopAdvertisersDTO>();
            foreach (var item in getSpend.Take(10))
            {
                var spendItem = new TopAdvertisersDTO();
                spendItem.Value = FormatNumber(Convert.ToInt64(item.Value));
                spendItem.Advertiser = item.Advertiser;
                spend.Add(spendItem);
                spendTotal += item.Value;
            }

            ViewBag.TotalSpend = FormatNumber(Convert.ToInt64(spendTotal));
            ViewBag.TopSpends = spend;
            
            //Pie chart category spend
            ViewBag.CategorySelection = "This year";
            if (search == "This Month")
            {
                beginDate = new SqlParameter("@BeginDate", firstDayOfMonth);
                endDate = new SqlParameter("@EndDate", firstDayOfMonth.AddMonths(1).AddDays(-1));
                ViewBag.CategorySelection = search;
            }
            else if (search == "Last Month")
            {
                beginDate = new SqlParameter("@BeginDate", firstDayOfMonth.AddMonths(-1));
                endDate = new SqlParameter("@EndDate", firstDayOfMonth.AddDays(-1));
                ViewBag.CategorySelection = search;
            }
            else
            {
                beginDate = new SqlParameter("@BeginDate", new DateTime(year, 1, 1));
                endDate = new SqlParameter("@EndDate", new DateTime(year, 12, 31));
            }

            var product = new SqlParameter("@ProductId", userDetails.CategoryId);
            var getBrands = db.TopBrandsInCategories.FromSqlRaw("onl_GetMediaSpendAllMediaByBrandAndCategory_sel @BeginDate, @EndDate, @ProductId", parameters: new[] { beginDate, endDate, product }).ToList().Take(5);

            var spendTotal2 = 0.00;
            foreach (var item in getBrands)
            {
                if (item.Brand == "MTN")
                {
                    item.Style = "bg-four";

MediaMonitoring/Views/Electronic/MediaSpendReport.cshtml
@model MediaMonitoring.Models.MediaSpendViewModel
@{
    ViewData["Title"] = "Media Spend Report";
    Layout = "~/Views/Shared/_LayoutElectronic.cshtml";
}

<p class="my-4 p-2"><a asp-controller="Electronic" asp-action="MediaSpend"><i class="fas fa-chevron-left px-2"></i>Go back</a></p>

<!-- DataTales Example -->
<div class="card mb-4">
    <div class="card-header py-3 bg-white">
        <h3 class="p-4 font-weight-bold text-black">Media Spend Report</h3>
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-6 mt-3 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-none border border-secondary medium" placeholder="Search a brand Name" aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="border border-secondary btn" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @if (Model.MediaSpends != null)
            {
                <div class="my-4 ml-4">
                    <form asp-action="Export" asp-controller="Electronic" asp-route-operation="MediaSpend" method="post">
                        <input type="hidden" name="GridHtml" />
                        <button type="submit" class="btn btn-secondary btnSubmit">Download a copy <i class="fas fa-download pl-4"></i></button>
                    </form>
                </div>
                <div id="Grid">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead class="bg-grey">
                            <tr class="text-black">
                                <th>Advertiser</th>
                                <th>Spots</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.MediaSpends)
                            {
                                <tr>
                                    <td>@item.Advertiser</td>
                                    <td>@item.Spots</td>
                                    <td>₦@item.Value</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else if (Model.MediaSpendByBrands != null)
            {
                <div class="my-4 ml-4">
                    <form asp-action="Export" asp-controller="Electronic" asp-route-operation="MediaSpendByBrand" method="post">
                        <input type="hidden" name="GridHtml" />
                        <button type="submit" class="btn btn-secondary btnSubmit">Download a copy <i class="fas fa-download pl-4"></i></button>
                    </form>
                </div>
                <div id="Grid">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead class="bg-grey">
                            <tr class="text-black">
                                <th>Brand</th>
                                <th>Spots</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.MediaSpendByBrands)
                            {
                                <tr>
                                    <td>@item.Brand</td>
                                    <td>@item.Spots</td>
                                    <td>₦@item.Value</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else if (Model.MediaSpendByProducts != null)
            {
                <div class="my-4 ml-4">
                    <form asp-action="Export" asp-controller="Electronic" asp-route-operation="MediaSpendByProducts" method="post">
                        <input type="hidden" name="GridHtml" />
                        <button type="submit" class="btn btn-secondary btnSubmit">Download a copy <i class="fas fa-download pl-4"></i></button>
                    </form>
                </div>
                <div id="Grid">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead class="bg-grey">
                            <tr class="text-black">
                                <th>Product Category</th>
                                <th>Spots</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.MediaSpendByProducts)
                            {
                                <tr>
                                    <td>@item.Product</td>
                                    <td>@item.Spots</td>
                                    <td>₦@item.Value</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $(".btnSubmit").click(function () {
                $("input[name='GridHtml']").val($("#Grid").html());
            });
        });

        $('ul.navbar-nav.sidebar.accordion li a').each(function () {
            if ($(this).hasClass('mediaspend')) {
                $(this).parent().addClass('active mt-4 text-center');
                $(this).children('i').addClass('acting');
            } else {
                $(this).parent().removeClass('active mt-4 text-center');
                $(this).children('i').removeClass('acting');
            }
        });
    </script>
}

MediaMonitoring/Views/Electronic/ReconciliationReport.cshtml
@model MediaMonitoring.Models.ReconciliationViewModel
@{
    ViewData["Title"] = "Reconciliation Report";
    Layout = "~/Views/Shared/_LayoutElectronic.cshtml";
}

<p class="my-4 p-2"><a asp-controller="Electronic" asp-action="Reconciliation"><i class="fas fa-chevron-left px-2"></i>Go back</a></p>

<!-- DataTales Example -->
<div class="card mb-4">
    <div class="card-header py-3 bg-white">
        <h3 class="p-4 font-weight-bold text-black">Reconciliation Report</h3>
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-6 mt-3 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-none border border-secondary medium" placeholder="Search a brand or Station" aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="border border-secondary btn" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @if (Model.Reconciliations != null)
            {
                <div class="my-4 ml-4">
                    <form asp-action="Export" asp-controller="Electronic" asp-route-operation="Reconciliation" method="post">
                        <input type="hidden" name="GridHtml" />
                        <button type="submit" class="btn btn-secondary btnSubmit">Download a copy <i class="fas fa-download pl-4"></i></button>
                    </form>
                </div>
                <div id="Grid">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead class="bg-grey">
                            <tr class="text-black">
                                <th>Station</th>
                                <th>Brand</th>
                                <th>Date</th>
                                <th>Program</th>
                                <th>Scheduled Time</th>
                                <th>Total Spots Booked</th>
                                <th>Total Compliance To Time</th>
                                <th>Captured Time</th>
                                <th>Extra Spots</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Reconciliations)
                            {
                                <tr>
                                    <td>@item.Stations</td>
                                    <td>@item.Brand</td>
                                    <td>@item.AdDate.ToShortDateString()</td>
                                    <td>@item.Program</td>
                                    <td>@item.ScheduledTime</td>
                                    <td>@item.ScheduledSpots</td>
                                    <td>@item.CapturedSpots</td>
                                    <td>@item.CapturedTime</td>
                                    <td>@item.ExtraSpots</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else if (Model.ReconciliationSummaries != null)
            {
                <div class="my-4 ml-4">
                    <form asp-action="Export" asp-controller="Electronic" asp-route-operation="ReconciliationRadio" method="post">
                        <input type="hidden" name="GridHtml" />
                        <button type="submit" class="btn btn-secondary btnSubmit">Download a copy <i class="fas fa-download pl-4"></i></button>
                    </form>
                </div>
                <div id="Grid">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead class="bg-grey">
                            <tr class="text-black">
                                <th>Station</th>
                                <th>Brand</th>
                                <th>Program</th>
                                <th>Scheduled Time</th>
                                <th>Number Scheduled</th>
                                <th>Number Detected</th>
                                <th>Extra Spots</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ReconciliationSummaries)
                            {
                                <tr>
                                    <td>@item.Stations</td>
                                    <td>@item.Brand</td>
                                    <td>@item.Program</td>
                                    <td>@item.ScheduledTime</td>
                                    <td>@item.NumberBooked</td>
                                    <td>@item.NumberCaptured</td>
                                    <td>@item.ExtraSpots</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $(".btnSubmit").click(function () {
                $("input[name='GridHtml']").val($("#Grid").html());
            });
        });

        $('ul.navbar-nav.sidebar.accordion li a').each(function () {
            if ($(this).hasClass('reconciliation')) {
                $(this).parent().addClass('active mt-4 text-center');
                $(this).children('i').addClass('acting');
            } else {
                $(this).parent().removeClass('active mt-4 text-center');
                $(this).children('i').removeClass('acting');
            }
        });
    </script>
}